// lib/waitlist.ts
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { Resend } from "resend";

type JoinWaitlistOptions = {
  email: string;
  zone?: string | null;
  noEmail?: boolean;
  name?: string | null;
  userAgent?: string | null;
  ip?: string | null;
  // Waitlist joins are single opt-in ("confirmed"); signup opt-ins stay "pending" until the account email is confirmed
  status?: "pending" | "confirmed";
  // Where they came from: "website", "signup", or a link's ?from= value such as "whatsapp"
  source?: string | null;
  // City picked on the waitlist form, to measure demand by city
  city?: string | null;
};

// Must fit newsletter_city_length_chk (1-60 chars)
function normalizeCity(value?: string | null) {
  const v = (value || "").replace(/\s+/g, " ").trim().slice(0, 60);
  return v || null;
}

// Must match newsletter_source_format_chk; anything else is recorded as a plain website signup
function normalizeSource(value?: string | null) {
  const v = (value || "").trim().toLowerCase();
  return /^[a-z0-9_-]{1,32}$/.test(v) ? v : "website";
}

export async function joinWaitlist({ email, zone, noEmail, name, userAgent, ip, status = "confirmed", source, city }: JoinWaitlistOptions) {
  const normalized = email.trim().toLowerCase();
  if (!/\S+@\S+\.\S+/.test(normalized)) {
    throw new Error("Invalid email.");
  }

  const cityValue = normalizeCity(city);

  // email_lc is generated by the database (lower(email)), so it must not be written here
  const { data: inserted, error } = await supabaseAdmin
    .from("newsletter")
    .insert([{ email: normalized, zone, user_agent: userAgent, ip, status, source: normalizeSource(source), city: cityValue }])
    .select("id")
    .single();

  if (error) {
    // Unique violation on email/email_lc: they're already on the list, which is a success for the visitor
    if (error.code === "23505") {
      // Fill in the city for people who joined before we asked for it
      if (cityValue) {
        const { error: cityErr } = await supabaseAdmin
          .from("newsletter")
          .update({ city: cityValue })
          .eq("email_lc", normalized)
          .is("city", null);
        if (cityErr) console.error("joinWaitlist: city backfill failed", cityErr);
      }
      return { id: null, already: true };
    }
    console.error("joinWaitlist: insert failed", error);
    throw new Error("Couldn’t add you to the waitlist. Please try again.");
  }

  if (noEmail) {
    return { id: inserted.id, silent: true };
  }

  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_API_KEY) {
    console.warn("joinWaitlist: RESEND_API_KEY is not set; skipping welcome email");
    return { id: inserted.id };
  }

  const resend = new Resend(RESEND_API_KEY);
  const { error: sendErr } = await resend.emails.send({
    from: "Velah <no-reply@drinkvelah.com>",
    to: normalized,
    subject: "You’re on the Velah waitlist",
    text: [
      `Hi${name ? " " + name : ""},`,
      "",
      "You’re on the Velah waitlist. We’ll reach out when your area opens.",
      "",
      "If you didn’t request this, you can ignore this message.",
      "",
      "Velah Team",
      "This is an automated message. Please do not reply.",
    ].join("\n"),
    html: `
      <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.6;color:#111">
        <p>Hi${name ? " " + name : ""},</p>
        <p>You’re on the <strong>Velah</strong> waitlist. We’ll email you when your area opens.</p>
        <p style="color:#777;font-size:12px;margin-top:24px">This is an automated message. Please do not reply.</p>
      </div>
    `,
  });
  if (sendErr) {
    // They're already saved on the list; a failed welcome email shouldn't fail the join
    console.error("joinWaitlist: welcome email failed", sendErr);
  }

  return { id: inserted.id };
}
